export interface LocationCoords {
  latitude: number;
  longitude: number;
}

export interface Ride {
  id: string;
  pickupLocation: string;
  dropoffLocation: string;
  pickupMarker: LocationCoords | null;
  dropoffMarker: LocationCoords | null;
  numberOfSeats: string;
  pricePerSeat: string;
  fullCarPrice: string;
  acEnabled: boolean;
  date: string;
  time: string;
  status: "upcoming" | "pending" | "ongoing" | "cancelled" | "completed";
  seatsBooked: number;
  passengerName: string;
  passengerImage: string;
  hasBookingRequests?: boolean;
  pendingRequestsCount?: number;
  hasMultiDayItineraryRequest?: boolean; // Add this new field
}

export const statusColors: Record<string, { bg: string; text: string }> = {
  upcoming: { bg: "#DBEAFE", text: "#1E40AF" },
  pending: { bg: "#FEF3C7", text: "#92400E" },
  ongoing: { bg: "#DCFCE7", text: "#166534" },
  completed: { bg: "#f0fdf4", text: "#15803d" },
  cancelled: { bg: "#FEE2E2", text: "#991B1B" },
};

// Explicitly type the array as Ride[]
const publishedRidesData: Ride[] = [
  {
    id: "1",
    pickupLocation: "Downtown Amman",
    dropoffLocation: "Queen Alia Airport",
    pickupMarker: { latitude: 31.9454, longitude: 35.9284 },
    dropoffMarker: { latitude: 31.7226, longitude: 35.9889 },
    numberOfSeats: "4",
    pricePerSeat: "15",
    fullCarPrice: "50",
    acEnabled: true,
    date: "2025-01-15",
    time: "10:30 AM",
    status: "ongoing",
    seatsBooked: 2,
    passengerName: "Ahmed Hassan",
    passengerImage: "https://i.pravatar.cc/150?img=1",
    hasBookingRequests: false,
    hasMultiDayItineraryRequest: false,
  },
  {
    id: "2",
    pickupLocation: "Abdoun Circle",
    dropoffLocation: "Sweifieh Mall",
    pickupMarker: { latitude: 31.9343, longitude: 35.8065 },
    dropoffMarker: { latitude: 31.9461, longitude: 35.7903 },
    numberOfSeats: "5",
    pricePerSeat: "8",
    fullCarPrice: "35",
    acEnabled: false,
    date: "2025-01-16",
    time: "2:45 PM",
    status: "pending",
    seatsBooked: 0,
    passengerName: "Fatima Al-Rashid",
    passengerImage: "https://i.pravatar.cc/150?img=2",
    hasBookingRequests: true,
    pendingRequestsCount: 3,
    hasMultiDayItineraryRequest: true,
  },
  {
    id: "3",
    pickupLocation: "Shmeisani",
    dropoffLocation: "Sports City",
    pickupMarker: { latitude: 31.9389, longitude: 35.7889 },
    dropoffMarker: { latitude: 31.9245, longitude: 35.8456 },
    numberOfSeats: "6",
    pricePerSeat: "10",
    fullCarPrice: "55",
    acEnabled: true,
    date: "2025-01-17",
    time: "8:00 AM",
    status: "pending",
    seatsBooked: 0,
    passengerName: "Mohammed Saleh",
    passengerImage: "https://i.pravatar.cc/150?img=3",
    hasBookingRequests: true,
    hasMultiDayItineraryRequest: true,
  },
  {
    id: "4",
    pickupLocation: "Jabal Amman",
    dropoffLocation: "Dead Sea",
    pickupMarker: { latitude: 31.945, longitude: 35.926 },
    dropoffMarker: { latitude: 31.477, longitude: 35.5 },
    numberOfSeats: "4",
    pricePerSeat: "25",
    fullCarPrice: "90",
    acEnabled: true,
    date: "2025-01-18",
    time: "6:00 PM",
    status: "ongoing",
    seatsBooked: 3,
    passengerName: "Layla Majed",
    passengerImage: "https://i.pravatar.cc/150?img=4",
    hasBookingRequests: false,
  },
  {
    id: "5",
    pickupLocation: "University of Jordan",
    dropoffLocation: "Rainbow Street",
    pickupMarker: { latitude: 31.94, longitude: 35.8 },
    dropoffMarker: { latitude: 31.9455, longitude: 35.9289 },
    numberOfSeats: "5",
    pricePerSeat: "7",
    fullCarPrice: "30",
    acEnabled: false,
    date: "2025-01-19",
    time: "3:30 PM",
    status: "pending",
    seatsBooked: 0,
    passengerName: "Randa Nasser",
    passengerImage: "https://i.pravatar.cc/150?img=5",
    hasBookingRequests: true,
    pendingRequestsCount: 1,
    hasMultiDayItineraryRequest: false,
  },
  {
    id: "6",
    pickupLocation: "Zarqa City",
    dropoffLocation: "Amman Center",
    pickupMarker: { latitude: 32.0726, longitude: 35.8653 },
    dropoffMarker: { latitude: 31.9454, longitude: 35.9284 },
    numberOfSeats: "6",
    pricePerSeat: "12",
    fullCarPrice: "65",
    acEnabled: true,
    date: "2025-01-20",
    time: "9:00 AM",
    status: "completed",
    seatsBooked: 4,
    passengerName: "Karim Yousef",
    passengerImage: "https://i.pravatar.cc/150?img=6",
    hasBookingRequests: false,
    hasMultiDayItineraryRequest: false,
  },
  {
    id: "7",
    pickupLocation: "Irbid",
    dropoffLocation: "Downtown Amman",
    pickupMarker: { latitude: 32.5564, longitude: 35.75 },
    dropoffMarker: { latitude: 31.9454, longitude: 35.9284 },
    numberOfSeats: "5",
    pricePerSeat: "20",
    fullCarPrice: "85",
    acEnabled: true,
    date: "2025-01-21",
    time: "11:00 AM",
    status: "pending",
    seatsBooked: 0,
    passengerName: "Dina Khalil",
    passengerImage: "https://i.pravatar.cc/150?img=7",
    hasBookingRequests: false,
  },
  {
    id: "8",
    pickupLocation: "Salt",
    dropoffLocation: "Amman Station",
    pickupMarker: { latitude: 31.9336, longitude: 35.7341 },
    dropoffMarker: { latitude: 31.9454, longitude: 35.9284 },
    numberOfSeats: "4",
    pricePerSeat: "18",
    fullCarPrice: "65",
    acEnabled: false,
    date: "2025-01-22",
    time: "4:00 PM",
    status: "cancelled",
    seatsBooked: 2,
    passengerName: "Samir Nassar",
    passengerImage: "https://i.pravatar.cc/150?img=8",
    hasBookingRequests: false,
    hasMultiDayItineraryRequest: false,
  },
  {
    id: "9",
    pickupLocation: "Mecca Street",
    dropoffLocation: "Abdali Mall",
    pickupMarker: { latitude: 31.95, longitude: 35.91 },
    dropoffMarker: { latitude: 31.9614, longitude: 35.9102 },
    numberOfSeats: "3",
    pricePerSeat: "6",
    fullCarPrice: "18",
    acEnabled: true,
    date: "2025-01-23",
    time: "1:00 PM",
    status: "pending",
    seatsBooked: 0,
    passengerName: "Omar Khaled",
    passengerImage: "https://i.pravatar.cc/150?img=9",
    hasBookingRequests: false,
    hasMultiDayItineraryRequest: false,
  },
  {
    id: "10",
    pickupLocation: "Gardens Street",
    dropoffLocation: "City Mall",
    pickupMarker: { latitude: 31.97, longitude: 35.88 },
    dropoffMarker: { latitude: 31.985, longitude: 35.865 },
    numberOfSeats: "4",
    pricePerSeat: "9",
    fullCarPrice: "35",
    acEnabled: true,
    date: "2025-01-24",
    time: "5:30 PM",
    status: "pending",
    seatsBooked: 0,
    passengerName: "Sarah Ahmad",
    passengerImage: "https://i.pravatar.cc/150?img=10",
    hasBookingRequests: true,
    pendingRequestsCount: 2,
    hasMultiDayItineraryRequest: false,
  },
];

export default publishedRidesData;
