export default {
  onboarding: {
    slide1: {
      title: "اطلب رحلة",
      description: "استعد. ابدأ رحلتك.",
    },
    slide2: {
      title: "ابحث عن رحلة",
      description: "رحلتك على بعد نقرة واحدة.",
    },
    slide3: {
      title: "اطلب رحلة",
      description: "استعد، ابدأ الرحلة",
    },
    slide4: {
      title: "انشر رحلة",
      description: "سافر معًا، وفر معًا.",
    },
    slide5: {
      title: "شارك رحلتك ووفر التكاليف",
      description:
        "يساعدك راكب على مشاركة الرحلات داخل الأردن وتقسيم تكاليف الوقود بطريقة ذكية وآمنة.",
    },
    slide6: {
      title: "اختر من تسافر معه",
      description:
        "تصفح ملفات السائقين، اقرأ التقييمات، واختر الرحلة المناسبة لك.",
    },
    slide7: {
      title: "سائق أو راكب بحساب واحد",
      description:
        "بدّل بسهولة بين وضع الراكب والسائق في أي وقت داخل نفس الحساب.",
    },
    slide8: {
      title: "فعّل موقعك",
      description: "اختر موقعك للبدء.",
      locationAccessGranted: "تم منح الوصول إلى الموقع",
      locationAccessRequired: "مطلوب الوصول إلى الموقع",
      skipforNow: "تخطي الآن",
      allSet: "كل شيء جاهز! اضغط على انطلق للمتابعة.",
      pickupTimes:
        "نحتاج إلى موقعك للعثور على رحلات قريبة وتوفير أوقات استلام دقيقة.",
      locationServiceDisabled: "خدمات الموقع معطلة",
      locationService: "يرجى تمكين خدمات الموقع في إعدادات جهازك للمتابعة.",
      locationPermission: "مطلوب إذن الوصول إلى الموقع",
      appInfo:
        "يحتاج هذا التطبيق إلى موقعك لتقديم خدمات قريبة ومعلومات دقيقة عن الرحلات. يرجى تمكين الوصول إلى الموقع في الإعدادات.",
      go: "انطلق",
    },
  },
  auth: {
    signUp: {
      title: "إنشاء حساب",
      subtitle: "أنشئ حسابك للبدء",
      agree1: "أوافق على",
      agree2: "الشروط والأحكام",
      agree3: "و",
      agree4: "سياسة الخصوصية",
      fields: {
        name: "الاسم",
        namePlaceholder: "أوليفيا راي",
        userName: "اسم المستخدم",
        userNamePlaceholder: "لتيسيا15",
        email: "البريد الإلكتروني",
        emailPlaceholder: "Olivia321@gmail.com",
        phone: "رقم الهاتف",
        phonePlaceholder: "٠٦ ١٢٣٤٥٦٧٨ ٣٩+",
        password: "كلمة المرور",
        passwordPlaceholder: "********",
        confirmPassword: "تأكيد كلمة المرور",
        confirmPasswordPlaceholder: "********",
        location: "الموقع",
        locationPlaceholder: "٢٩٥٥ شارع واشترمير، منطقة سانتا، سان فرانسيسكو",
        bio: "السيرة الذاتية",
        bioPlaceholder: "بحد أقصى 150 حرفًا...",
      },
      button: "إنشاء حساب",
      editButton: "تحديث الملف الشخصي",
      googleButton: "المتابعة مع جوجل",
      footer: {
        text: "لديك حساب بالفعل؟",
        link: "تسجيل الدخول",
      },
    },
    logIn: {
      title: "تسجيل الدخول",
      subtitle: "الوصول إلى حسابك",
      fields: {
        email: "البريد الإلكتروني",
        emailPlaceholder: "Olivia321@gmail.com",
        password: "كلمة المرور",
        passwordPlaceholder: "********",
      },
      forgotPassword: "نسيت كلمة المرور؟",
      button: "تسجيل الدخول",
      or: "أو",
      googleButton: "المتابعة مع جوجل",
      footer: {
        text: "ليس لديك حساب؟",
        link: "إنشاء حساب",
      },
    },
    verifyNumber: {
      title: "تحقق من رقم الهاتف",
      subtitle: "أدخل رمز الرسالة النصية الذي أرسلناه",
      buttonTitle: "تحقق",
      resend: "إعادة إرسال الرمز",
      verifySuccessTitle: "تم التحقق بنجاح!",
      verifySuccessSubtitle: "تم التحقق من رقم هاتفك بنجاح",
      continue: "متابعة",
    },
    forgotPassword: {
      title: "نسيت كلمة المرور",
      subtitle: "يرجى إدخال عنوان البريد الإلكتروني للمتابعة والتحقق من حسابك",
      send: "إرسال",
    },
    verifyPassword: {
      title: "رمز التحقق",
      subtitle:
        "يرجى إدخال الرمز المكون من 6 أرقام المرسل إلى عنوان بريدك الإلكتروني ********r@gmail.com",
      modalTitle: "تهانينا!",
      modalSubtitle: "تم تعيين كلمة المرور بنجاح",
    },

    setPassword: {
      title: "تعيين كلمة مرور جديدة",
      subtitle: "قم بتعيين كلمة المرور الجديدة الخاصة بك",
      passwordHeader: "أدخل كلمة مرور جديدة",
      confirmPassword: "تأكيد كلمة المرور",
      buttonText: "إعادة التعيين",
      modalSubtitle: "تمت إعادة تعيين كلمة المرور بنجاح",
    },
    allButtonsName: {
      passenger: "ابدأ كراكب",
      driver: "ابدأ كسائق",
    },
    shared: {
      genderTitle: "التفضيلات العامة",
      male: "ذكر",
      female: "أنثى",
      noPreference: "بدون تفضيل",
    },
  },

  tabs: {
    map: {
      bookNow: "احجز الآن",
      scheduleRide: "جدولة رحلة",
      titlePlaceholder: "إلى أين تريد الذهاب؟",
      pickUpLocation: "موقع الاستلام",
      DroppingOff: "موقع التوصيل",
    },
    profile: {
      editProfile: "تعديل الملف الشخصي",
      changePassword: "تغيير كلمة المرور",
      savedDriver: "السائق المحفوظ",
      payments: "المدفوعات",
      preferences: "التفضيلات",
      helpAndSupport: "المساعدة والدعم",
      terms: "الشروط والأحكام",
      privacy: "سياسة الخصوصية",
      logout: "تسجيل الخروج",
      myvehicle: "مركبتي",
      dashboard: "لوحة التحكم",
      changePasswordScreen: {
        enterCurrentPass: "أدخل كلمة المرور الحالية",
        enterNewPass: "أدخل كلمة المرور الجديدة",
        enterconfirmPass: "أدخل تأكيد كلمة المرور",
        changePass: "حفظ التغييرات",
      },
      changeLanguage: "تغيير اللغة",
      settings: "الإعدادات",
      myRides: "رحلاتي",
    },
  },

  passenger: {
    availableRides: {
      confirmRide: "تأكيد الرحلة",
      bookSeats: "حجز",
      seat: "مقعد",
      seats: "مقاعد",
      with: "مع",
      total: "الإجمالي",
      genderPreference: "تفضيل الجنس",
      male: "ذكر",
      female: "أنثى",
      any: "أي",
      chat: "دردشة",
      call: "اتصال",
      bookNow: "احجز الآن",
      booked: "محجوز",
      noRidesAvailable: "لا توجد رحلات متاحة في الوقت الحالي",
      backToTripRequest: "العودة إلى طلب الرحلة",
      numberOfSeats: "عدد المقاعد",
      seatsAvailable: "مقاعد متاحة",
      bookFullCar: "احجز السيارة كاملة",
      openingChat: "فتح الدردشة مع",
      calling: "جاري الاتصال",
      success: "نجاح",
      bookingSuccess: "تم حجز المقاعد مع",
    },

    tabs: {
      titles: {
        home: "الرئيسية",
        myTrip: "رحلاتي",
        chats: "المحادثات",
        profile: "الملف الشخصي",
        messages: "الرسائل",
      },

      home: {
        driverRequestList: "قائمة السائقين المتاحين",
        noDriverAvailable: "لا يوجد سائقون متاحون",
        arrivingIn: "سيصل خلال",
        mins: "mins",
        chat: "دردشة",
        call: "اتصال",
        accept: "قبول",
        cancel: "إلغاء",
        ridesShared: "الرحلات المشتركة",
        cancelled: "تم الإلغاء",
        ratings: "التقييمات",
        reviews: "المراجعات",
        report: "إبلاغ",
        block: "حظر",
        reportDriver: "الإبلاغ عن السائق",
        selectReason: "اختر سببًا",
        submitReport: "إرسال البلاغ",
        describeTheIssue: "يرجى وصف المشكلة",

        describeWhatHappend: "صف ما حدث...",
        unsafeDriving: "قيادة غير آمنة",
        rude: "سلوك غير مهذب",
        carCondition: "مشاكل في حالة السيارة",
        conduct: "سلوك غير لائق",
        cancelledMultipleTimes: "تم الإلغاء عدة مرات",
        other: "أخرى",

        blockDriver: "حظر السائق؟",
        confirm: "هل أنت متأكد أنك تريد الحظر؟",
        confirm2: "لن تتمكن من رؤية رحلاته أو التواصل معه.",
        yesBlock: "نعم، حظر السائق",
      },

      trip: {
        titles: {
          pickADate: "اختر التاريخ",
          pickATime: "اختر الوقت",
          selectLuggage: "اختر الأمتعة",
          selectPreferredGender: "اختر الجنس المفضل",
          tripSummary: "ملخص الرحلة",
          tripDetails: "تفاصيل الرحلة",
          driverProfile: "ملف السائق",
          rideCancellation: "إلغاء الرحلة",
          termsConditions: "الشروط والأحكام",
          privacyPolicy: "سياسة الخصوصية",
          rating: "التقييم",
          availableRides: "الرحلات المتاحة",
          cancelledRides: "الرحلات الملغاة",
          ridesShared: "الرحلات المشتركة",
          aboutUs: "معلومات عنا",
        },

        selectDate: "اختر التاريخ",
        selectTime: "اختر الوقت",
        howManyseats: "كم عدد المقاعد التي تبحث عنها؟",
        luggageSize: "حجم الأمتعة",
        next: "التالي",
        generalPreferences: "التفضيلات العامة",
        pickUplocation: "موقع الانطلاق",
        dropOffLocation: "موقع الوصول",
        tripDate: "تاريخ المغادرة",
        tripTime: "وقت المغادرة",
        distance: "المسافة",
        seat: "المقعد",
        genderPreference: "تفضيل الجنس",
        multiDaySelection: "خط سير متعدد التوقفات",
        yourRoute: "مسارك",
        stops: "محطات",
        stop: "محطة",
        addStop: "إضافة محطة",
        publishRequest: "نشر الطلب",
        chatWithDriver: "الدردشة مع السائق",
        viewTrip: "عرض الرحلة",
        backtoHome: "العودة إلى الصفحة الرئيسية",
        selectedLocation: "المواقع المحددة",
        pickUp: "الانطلاق",
        dropoff: "الوصول",
        cancelRide: "إلغاء الرحلة",
        continue: "متابعة",
        cancelModalTitle: "هل أنت متأكد أنك تريد الإلغاء؟",
        yesBtn: "نعم",
        noBtn: "لا",

        continueModalTitle: "لقد وصلت إلى وجهتك",
        continueModalSubtitle: "اكتملت الرحلة",

        leaveReview: "اترك مراجعة",
        goBack: "ارجع",

        selectDriver: {
          confirmRide: "تأكيد الرحلة",
          bookSeats: "احجز",
          seat: "مقعد",
          seats: "مقاعد",
          with: "مع",
          total: "الإجمالي",
          success: "نجاح",
          bookedSuccess: "تم حجز",
          cancelRequest: "إلغاء الطلب",
          areYouSureCancel: "هل أنت متأكد من رغبتك في إلغاء هذا الطلب؟",
          premiumFeature: "ميزة متميزة",
          callFeatureMessage:
            "ميزة الاتصال متاحة فقط للمستخدمين المتميزين. قم بترقية حسابك لتفعيل الاتصال.",
          upgradeNow: "ترقية الآن",
        },
      },

      ratingScreenText: {
        headerTitle: "قيّم تجربتك",
        headerSubtitle: "ملاحظاتك تساعدنا على التحسين",
        ratingLabels: {
          1: "سيئ",
          2: "مقبول",
          3: "جيد",
          4: "جيد جدًا",
          5: "ممتاز",
        },
        commentPlaceholder: "اكتب تعليقًا قصيرًا..",
        submitBtn: "إرسال",
        notNowBtn: "ليس الآن",
      },

      profileScreenText: {
        currentModePrefix: "أنت الآن في ",
        passenger: "راكب",
        driver: "سائق",
        modeSuffix: " وضع",
        enableDriverMode: "تفعيل وضع السائق",
        enablePassengerMode: "تفعيل وضع الراكب",

        titles: {
          profileSetup: "إعداد الملف الشخصي",
          editProfile: "تعديل الملف الشخصي",
          changePassword: "تغيير كلمة المرور",
          savedDriver: "السائقون المحفوظون",
          payments: "المدفوعات",
          cashInput: "إدخال نقدي",
          transactionsHistory: "سجل المعاملات",
          preference: "تفضيلات الرحلة",
          helpAndSupport: "المساعدة والدعم",
        },

        logout: {
          logoutText:
            "هل أنت متأكد أنك تريد تسجيل الخروج؟ ستحتاج إلى تسجيل الدخول مرة أخرى للوصول إلى حسابك.",
          logoutBtn: "تسجيل الخروج",
          cancel: "إلغاء",
        },
        ridePreferenceScreenText: {
          ladiesOnlyPreference: "تفضيل للسيدات فقط",
          luggazeSize: "حجم الأمتعة",
          conversationalPreference: "تفضيل المحادثة",
          talkative: "كثير الكلام",
          quite: "هادئ",
          musicPreference: "تفضيل الموسيقى",
          pet: "مسموح باصطحاب الحيوانات الأليفة",
          saveBtn: "حفظ",
        },
        helpAndSupportScreenText: {
          frequentlyAskedQuestion: "الأسئلة الشائعة",
          needMoreHelp: "هل تحتاج إلى مزيد من المساعدة؟",
          contactSupport: "اتصل بالدعم",
        },
      },

      paymentScreenTexts: {
        header: {
          amount: "المبلغ",
          availableBalance: "الرصيد المتاح",
          addNewCard: "+أضف بطاقة جديدة",
          history: "السجل",
        },
        section: {
          selectPaymentMethod: "اختر طريقة الدفع",
        },
        methods: {
          cash: "نقدًا",
          wallet: "المحفظة",
          paypal: "باي بال",
          card: "بطاقة ائتمان",
          cliq: "كليك",
          comingSoon: "قريبًا",
        },
        actions: {
          payWith: "ادفع بواسطة",
          topUp: "شحن الرصيد",
          proceed: "متابعة",
          enterCash: "أدخل المبلغ النقدي",
        },
        modal: {
          notAvailableTitle: "غير متاح بعد",
          notAvailableMessage:
            "خيار الدفع عبر {method} سيكون متاحًا قريبًا. يرجى استخدام النقد الآن.",
          gotIt: "تم",
        },
      },
    },
  },

  driver: {
    profileLayoutTitleText: {
      driverProfileSetup: "إعداد الملف الشخصي",
      addVehicle: "إضافة مركبة",
      addVehicleDetails: "إضافة مركبة",
      vehicleSummary: "تفاصيل السيارة",
      passengerRqstList: "قائمة طلبات الركاب",
      passengerRqstDetails: "تفاصيل طلب الراكب",
    },

    rideDetail: {
      tripId: "رقم الرحلة",
      pickup: "نقطة الانطلاق",
      dropoff: "نقطة الوصول",
      dateTime: "تاريخ ووقت المغادرة",
      distance: "المسافة",
      seats: "المقاعد",
      price: "السعر",
      offeredPrice: "عرض",
      driver: "سائق",
      fullCarPrice: "السعر الكامل للسيارة",
    },

    driverProfileTexts: {
      nidUpload: "تحميل البطاقة الوطنية / الرخصة",
      firstNameLabel: "الاسم الأول",
      firstNamePlaceholder: "اكتب اسمك الأول",
      lastNameLabel: "اسم العائلة",
      lastNamePlaceholder: "اكتب اسم العائلة",
      licenseNumberLabel: "رقم الرخصة",
      licenseNumberPlaceholder: "رقم الرخصة",
      saveButton: "حفظ",
      permissionTitle: "مطلوب إذن",
      permissionMessage: "يرجى منح الإذن للوصول إلى مكتبة الصور الخاصة بك.",
      uploadTitle: "قم برفع صورة واضحة",
      uploadMessage: "اختر طريقة الرفع",
      photoLibrary: "مكتبة الصور",
      camera: "الكاميرا",
      cancel: "إلغاء",
      errorTitle: "خطأ",
      errorMessage: "فشل في اختيار الملف. يرجى المحاولة مرة أخرى.",
      tapToChange: "اضغط لتغيير الملف",
      clickToUpload: "اضغط للرفع",
      label: "تاريخ الميلاد",
      placeholder: "شهر/يوم/سنة",
      done: "تم",
      language: "اللغة",
      selectLanguage: "اختر اللغة",
      governorateLabel: "المحافظة",
      selectGovernorate: "اختر محافظتك",
      modalTitle: "اختر المحافظة",
      searchPlaceholder: "ابحث عن المحافظة...",
    },

    carImageUploadTexts: {
      permissionTitle: "مطلوب إذن",
      permissionGallery: "نحتاج إلى إذن للوصول إلى معرض الصور لرفع الصور.",
      permissionCamera: "نحتاج إلى إذن لاستخدام الكاميرا لالتقاط الصور.",
      removeImageTitle: "إزالة الصورة",
      removeImageMessage: "هل أنت متأكد أنك تريد إزالة هذه الصورة؟",
      cancel: "إلغاء",
      remove: "إزالة",
      addPhotosTitle: "إضافة صور",
      addPhotosMessage: "اختر خيارًا",
      takePhoto: "التقاط صورة",
      chooseFromGallery: "اختر من المعرض",
      addPhotoButton: "إضافة صورة",
      headerTitle: "معرض السيارة",
      headerSubtitle: "التقط أو ارفع صور سيارتك",
      photo: "صورة",
      photos: "صور",
      added: "تمت الإضافة",
      clearAllTitle: "مسح جميع الصور",
      clearAllMessage: "سيؤدي هذا إلى إزالة جميع الصور من المعرض.",
      clearAllButton: "مسح الكل",
      galleryTitle: "معرض الصور",
      noPhotos: "لا توجد صور بعد",
      startMessage: "ابدأ بالتقاط صورة أو الرفع من المعرض",
      gallery: "المعرض",
      close: "إغلاق",
      delete: "حذف",
      navigationPrev: "السابق",
      navigationNext: "التالي",
    },

    addVehicleDetails: {
      carModel: "طراز السيارة",
      carModelPlaceholder: "مثال: تويوتا أكسيو 2018",
      licensePlate: "لوحة الترخيص",
      licensePlatePlaceholder: "مثال: DHA-123456",
      numberOfSeats: "عدد المقاعد",
      numberOfSeatsPlaceholder: "مثال: 4",
      save: "حفظ",
      vehicleType: "نوع المركبة",
      vehicleTypePlaceholder: "اختر نوع المركبة",
      vehicleTypeTitle: "اختر نوع المركبة",
      amenities: {
        ac: "تكييف الهواء",
        usb: "منافذ USB",
        wifi: "واي فاي",
        smoking: "التدخين مسموح",
        music: "الموسيقى",
      },
    },

    vehicleSummary: {
      submit: "إرسال",
      carModel: "طراز السيارة",
      vehicleType: "نوع المركبة",
      numberOfSeats: "عدد المقاعد",
      trunkSize: "حجم الصندوق",
      trunkSizeValue: "وسط",
      amenities: {
        ac: "تكييف الهواء",
        usb: "منافذ USB",
        wifi: "واي فاي",
        smoking: "التدخين مسموح",
        music: "الموسيقى",
      },
    },

    tabs: {
      labels: {
        upcoming: "قادمة",
        ongoing: "جارية",
        requests: "طلباتي",
        completed: "مكتملة",
        cancelled: "ملغاة",

        // Ride sections
        publishedRequest: "رحلات منشورة",
        upcomingRides: "القادمة",
        ongoingRides: "الجارية",
        rideRequests: "الطلبات",
        completedRides: "المكتملة",
        cancelledRides: "الملغاة",
      },
      editRequestModal: {
        editRequest: "تعديل الطلب",
        tripId: "معرف الرحلة",
        pickupAddress: "عنوان الاستلام",
        searchPickup: "ابحث عن موقع الاستلام",
        dropoffAddress: "عنوان التوصيل",
        searchDropoff: "ابحث عن موقع التوصيل",
        date: "التاريخ",
        time: "الوقت",
        seats: "المقاعد",
        numberOfSeats: "عدد المقاعد",
        cancel: "إلغاء",
        saveChanges: "حفظ التغييرات",
        error: "خطأ",
        fillAllFields: "يرجى ملء جميع الحقول المطلوبة",
      },

      upcomingScreen: {
        emptyTitle: "لا توجد رحلات قادمة",
        editTime: "تعديل الوقت",
        viewDetails: "عرض التفاصيل",

        rideId: "رحلة",
        at: "في",
        status: {
          upcoming: "قادمة",
          ongoing: "جارية",
          completed: "مكتملة",
          cancelled: "ملغاة",
        },
        seats: "المقاعد",
        available: "متاح",
        pricePerSeat: "السعر/المقعد",
        fullCar: "السيارة الكاملة",
        ac: "تكييف الهواء",
        yes: "نعم",
        no: "لا",
        seatsBooked: "المقاعد المحجوزة",
        contact: "التواصل",
        cancel: "إلغاء",
        noUpcomingRides: "لا توجد رحلات قادمة",
        noUpcomingRidesMessage: "ليس لديك أي رحلات مجدولة",
      },
      ongoingRides: {
        emptyTitle: "لا توجد رحلات جارية",
        contactDriver: "التواصل مع السائق",
        cancel: "إلغاء",
        cancelTitle: "إلغاء الرحلة",
        cancelMessage: "هل أنت متأكد أنك تريد إلغاء هذه الرحلة؟",
        no: "لا",
        yesCancel: "نعم، إلغاء",

        rideId: "رحلة",
        pricePerSeat: "السعر لكل مقعد",
        seatsBooked: "المقاعد المحجوزة",
        contact: "التواصل",
        success: "نجاح",
        rideMarkedComplete: "تم تحديد الرحلة كمكتملة",
        noOngoingRides: "لا توجد رحلات جارية",
        noOngoingRidesMessage: "لا توجد رحلات جارية في الوقت الحالي",
      },
      requests: {
        emptyTitle: "لا توجد طلبات رحلات",
        accept: "قبول",
        decline: "رفض",
        successTitle: "تم بنجاح",
        successMessage: "تم قبول الطلب! سيتواصل معك السائق قريبًا.",
        rejectTitle: "تم رفض الطلب",
        rejectMessage: "لقد قمت برفض طلب الرحلة هذا.",
        ok: "حسنًا",
      },
      // Add this under driver.tabs in your ar.ts file:

      requestsScreen: {
        successTitle: "نجاح",
        acceptedOffer: "لقد قبلت عرض السائق",
        rejectTitle: "تم رفض الطلب",
        rejectMessage: "لقد قمت برفض طلب الرحلة هذا.",
        ok: "حسنًا",
        success: "نجاح",
        requestUpdated: "تم تحديث الطلب بنجاح",
        accept: "قبول",
        decline: "رفض",
        edit: "تعديل",
        cancel: "إلغاء",
        emptyTitle: "لا توجد طلبات رحلات",
      },
      completedScreen: {
        emptyTitle: "لا توجد رحلات مكتملة",
        rateDriver: "تقييم السائق",
        viewReceipt: "عرض الإيصال",

        rideId: "رحلة",
        at: "في",
        status: {
          upcoming: "قادمة",
          ongoing: "جارية",
          completed: "مكتملة",
          cancelled: "ملغاة",
        },
        seats: "المقاعد",
        available: "متاح",
        pricePerSeat: "السعر/المقعد",
        fullCar: "السيارة الكاملة",
        ac: "تكييف الهواء",
        yes: "نعم",
        no: "لا",
        seatsBooked: "المقاعد المحجوزة",
        rideCompletedSuccessfully: "تم إكمال الرحلة بنجاح",
        noCompletedRides: "لا توجد رحلات مكتملة",
        noCompletedRidesMessage: "ليس لديك أي رحلات مكتملة بعد",
        reviewPassenger: "تقييم الراكب",
      },
      cancelledScreen: {
        emptyTitle: "لا توجد رحلات ملغاة",
        bookAgain: "احجز مرة أخرى",
        viewDetails: "عرض التفاصيل",

        rideId: "رحلة",
        at: "في",
        status: {
          upcoming: "قادمة",
          ongoing: "جارية",
          completed: "مكتملة",
          cancelled: "ملغاة",
        },
        seats: "المقاعد",
        available: "متاح",
        pricePerSeat: "السعر/المقعد",
        fullCar: "السيارة الكاملة",
        ac: "تكييف الهواء",
        yes: "نعم",
        no: "لا",
        seatsBooked: "المقاعد المحجوزة",
        rideCancelled: "تم إلغاء الرحلة",
        noCancelledRides: "لا توجد رحلات ملغاة",
        noCancelledRidesMessage: "ليس لديك أي رحلات ملغاة",
      },
      membershipPlans: {
        header: "اختر خطتك",
        subheader: "اختر خطة العضوية المثالية",
        popular: "شائع",
        planBenefitsTitle: "مزايا الخطة",
        planBenefits:
          "• إلغاء في أي وقت بدون رسوم مخفية\n• ضمان استعادة الأموال خلال 14 يومًا\n• ترقية أو تخفيض الخطط بسهولة\n• معالجة دفع آمنة",
        freePlan: {
          name: "الخطة المجانية",
          buttonText: "ابدأ مجانًا",
          features: [
            "3 رحلات شهريًا",
            "إرسال الطلبات",
            "ملف شخصي أساسي",
            "دردشة داخل التطبيق",
          ],
        },
        premium: {
          name: "بريميوم",
          title: "كل شيء في الخطة المجانية +",
          buttonText: "ترقية",
          features: [
            "رحلات غير محدودة في وضع واحد: راكب أو سائق",
            "شارة زرقاء موثقة",
            "فلاتر أمان (الجنس، المستخدمون الموثقون)",
            "أولوية الظهور (فوق مستخدمي الخطة المجانية)",
            "مكالمات صوتية داخل التطبيق",
          ],
        },
        allAccess: {
          name: "الوصول الكامل",
          title: "كل شيء في خطة بريميوم +",
          buttonText: "احصل على الوصول الكامل",
          features: [
            "رحلات غير محدودة في كلا الوضعين: راكب وسائق",
            "شارة ذهبية",
            "ظهور أعلى من مستخدمي بريميوم",
            "تبديل الأوضاع في أي وقت بدون قيود",
            "ترتيب أعلى في نتائج البحث",
          ],
        },
        premiumPlus: {
          name: "بريميوم بلس",
          title: "كل شيء في خطة الوصول الكامل +",
          buttonText: "احصل على بلس",
          features: [
            "شارة بنفسجية",
            "أعلى ظهور: أولوية قصوى",
            "موضع مميز في نتائج البحث",
            "دعم بريميوم: دردشة مباشرة مع المشرف",
            "وصول كامل إلى المكافآت والمزايا المستقبلية",
            "وصول مبكر إلى الميزات الجديدة",
          ],
        },
      },

      homeScreenText: {
        publishARide: "نشر رحلة",
      },
      upcomingRides: {
        header: "الرحلات القادمة",
        noRides: "لا توجد رحلات مجدولة لهذا التاريخ.",
      },
      editRoutes: {
        required: "مطلوب",
        enterPickupLocation: "يرجى إدخال موقع الاستلام",
        enterDropoffLocation: "يرجى إدخال موقع التوصيل",
      },
      earnings: {
        estEarnings: "الأرباح المقدرة",
      },
      passengerRequestList: {
        successTitle: "نجاح",
        reportSubmitted: "تم إرسال البلاغ بنجاح",
        passengerBlocked: "تم حظر الراكب",
        seats: "مقاعد",
        km: "كم",
        openRequest: "فتح الطلب",
        reportUser: "الإبلاغ عن راكب",
        blockUser: "حظر الراكب",
      },
      passengerRequestDetails: {
        pickupLocation: "موقع الاستلام",
        dropoffLocation: "موقع التوصيل",
        tripDate: "تاريخ الرحلة",
        tripTime: "وقت الرحلة",
        distance: "المسافة",
        seat: "المقعد",
        luggageSize: "حجم الأمتعة",
        genderPreference: "تفضيل الجنس",
        multiDaySelection: "اختيار متعدد الأيام",
        sendOffer: "إرسال عرض",
      },
      sendOfferModal: {
        typeYourOffer: "اكتب عرضك",
        placeholder: "اكتب عرضك هنا (بالدينار الأردني)",
        cancel: "إلغاء",
        text1_empty: "العرض فارغ",
        text2_empty: "يرجى إدخال عرضك قبل الإرسال",
        text1_sending: "جاري إرسال العرض",
        text2_sending: "يرجى الانتظار...",
        text1_success: "تم إرسال العرض بنجاح",
        text2_success: "تم إرسال عرضك إلى الراكب. سنخطرك عندما يرد.",
      },

      completedRides: {
        completedRidesFor: "الرحلات المكتملة في",
        noRides: "لا توجد رحلات لهذا الشهر.",
        months: {
          january: "يناير",
          february: "فبراير",
          march: "مارس",
          april: "أبريل",
          may: "مايو",
          june: "يونيو",
          july: "يوليو",
          august: "أغسطس",
          september: "سبتمبر",
          october: "أكتوبر",
          november: "نوفمبر",
          december: "ديسمبر",
        },
      },

      map: {
        bookNow: "احجز الآن",
        scheduleRide: "جدولة رحلة",
        titlePlaceholder: "إلى أين تريد الذهاب؟",
        pickUpLocation: "موقع الاستلام",
        DroppingOff: "موقع التوصيل",
      },
      location: {
        permissionDenied: "تم رفض الإذن",
        permissionRequired: "مطلوب إذن الموقع لاستخدام هذه الميزة.",
        error: "خطأ",
        unableToGetLocation: "غير قادر على الحصول على الموقع الحالي",
        unableToGetLocationDetails: "غير قادر على الحصول على تفاصيل الموقع",
        selectedLocations: "المواقع المحددة:",
        pickup: "الاستلام:",
        dropoff: "التوصيل:",
        latitude: "خط العرض",
        longitude: "خط الطول",
      },

      myTrip: {
        screenTitles: {
          bookDate: "اختر تاريخ",
          bookTime: "اختر وقت",
          passengerProfile: "ملف الراكب",
        },

        publishedRides: {
          header: "رحلاتي المنشورة",
          activeRides: "رحلة",
          activeSuffix: " نشطة",
          noActiveRides: "لا توجد رحلات نشطة",
          completedAndCancelledMessage: "رحلاتك المكتملة والملغاة لا تظهر هنا",
          editRideModal: "تعديل الرحلة",
          saveChanges: "حفظ التغييرات",
          cancel: "إلغاء",
          selectLocation: "اختر الموقع",
          selectDate: "اختر التاريخ",
          selectTime: "اختر الوقت",
          pickupLabel: "موقع الاستلام",
          dropoffLabel: "موقع التوصيل",
          dateLabel: "تاريخ الرحلة",
          timeLabel: "وقت الرحلة",
          seatsLabel: "عدد المقاعد",
          pricePerSeatLabel: "السعر لكل مقعد (د.ا)",
          fullCarPriceLabel: "سعر السيارة الكاملة (د.ا)",
          acLabel: "تكييف الهواء",
          editButton: "تعديل",
          cancelButton: "إلغاء",
          markCompleted: "تحديد كمكتملة",
          deleteConfirmTitle: "إلغاء الرحلة",
          deleteConfirmMessage: "هل أنت متأكد من رغبتك في إلغاء هذه الرحلة؟",
          deleteConfirmNo: "لا",
          deleteConfirmYes: "نعم، إلغاء",
          updateSuccess: "نجاح",
          updateSuccessMessage: "تم تحديث تفاصيل الرحلة بنجاح!",
          locationPickerTitle: "اختر موقع الاستلام",
          locationPickerSubtitle: "اختر موقع التوصيل",
          searchLocation: "ابحث عن موقع...",
          noLocationsFound: "لم يتم العثور على مواقع",
          latitudeLabel: "خط العرض",
          longitudeLabel: "خط الطول",
        },

        // For RideCard component translations
        rideCard: {
          seats: "إجمالي المقاعد",
          available: "متاح",
          perSeat: "لكل مقعد",
          fullCar: "السيارة الكاملة",
          ac: "تكييف",
          acYes: "✓ نعم",
          acNo: "✗ لا",
          pending: "قيد الانتظار",
          ongoing: "جاري",
          completed: "مكتملة",
          cancelled: "ملغاة",
        },

        numberOfSeat: "عدد المقاعد",
        numberOfSeatPlaceholder: "مثال: مقعد واحد/سيارة كاملة",
        pricePerSeat: "السعر لكل مقعد",
        pricePerSeatPlaceholder: "مثال: مقعد واحد/سيارة كاملة",
        fullCarPrice: "سعر السيارة الكاملة",
        fullCarPricePlaceholder: "مثال: 40 دينار أردني للسيارة الكاملة",
        ladiesOnlyPreference: "تفضيل النساء فقط",
        next: "التالي",
        publishSuccess: {
          title: "تم نشر رحلتك.",
          subtitle: "سنخبرك عند قبول رحلتك.",
          done: "تم",
        },
      },

      profileScreenText: {
        screenTitles: {
          editProfile: "تعديل الملف الشخصي",
          myVehicle: "مركبتي",
          dashboard: "نظرة عامة",
          editAvailability: "تعديل التوفر",
          editRoutes: "تعديل المسارات",
          changeMembership: "اختر العضوية",
          completedRides: "الرحلات المكتملة",
          upcomingRides: "الرحلات القادمة",
          estimateEarning: "الأرباح",
        },
      },

      overview: {
        completedRides: "الرحلات\nالمكتملة",
        upcomingRides: "الرحلات\nالقادمة",
        estimatedEarnings: "الأرباح\nالمقدرة",
        editAvailability: "تعديل التوفر",
        editRoutes: "تعديل المسارات",
        viewPassengersRequestList: "طلبات الركاب",
        changeMembership: "تغيير العضوية",
        availability: "التوفر",
      },
    },
  },

  languageChange: {
    header: "تفضيلات اللغة",
    selectYourPreferredLanguage: "اختر لغتك المفضلة للتطبيق",
    currentLanguage: "اللغة الحالية",
    chooseLanguage: "اختر اللغة",
    languageInfo: "إعدادات اللغة",
    languageDescription:
      "سيتم حفظ اختيارك وتطبيقه على كل التطبيق. يمكنك تغيير هذا في أي وقت.",
    selectedLanguage: "تفاصيل اللغة المحددة",
    languageName: "اسم اللغة",
    languageCode: "رمز اللغة",
  },

  shared: {
    rakibPaymentForm: {
      unlimitedModeModal: {
        selectMode: "اختر الوضع",
        passengerModeOnly: "وضع الراكب فقط",
        driverModeOnly: "وضع السائق فقط",
      },

      formSheet: {
        formsheetTitle: "ماذا تريد أن تفعل؟",
      },

      titles: {
        premium: "ترقية إلى خطة بريميوم",
        allAccess: "ترقية إلى خطة الوصول الكامل",
        premiumPlus: "ترقية إلى خطة بريميوم بلس",
      },

      chooseUnlimitedMode: "اختر وضع غير محدود",
      selectMode: "اختر الوضع",
      wantUnlimitedRides: "هل تريد رحلات غير محدودة في أوضاع الراكب والسائق؟",
      upgradeToAllAccess: "الترقية إلى All Access",
      rakibUsername: "اسم مستخدم Rakib",
      rakibUsernamePlaceholder: "اكتب اسم المستخدم الخاص بك",
      fullName: "الاسم الكامل",
      fullNamePlaceholder: "اكتب اسمك الكامل",
      emailUsedOnRakib: "البريد الإلكتروني المستخدم في Rakib",
      emailPlaceholder: "اكتب بريدك الإلكتروني..",
      phoneNumberInternational: "رقم الهاتف (دولي)",
      phoneNumberPlaceholder: "+962...",
      payNowWithCreditCard: "الدفع الآن ببطاقة الائتمان (قريباً)",
      receivePaymentInfoByEmail: "استقبال معلومات الدفع عبر البريد الإلكتروني",
      monthly: "شهري، 4 دينار أردني",
      yearly: "سنوي، 40 دينار أردني",
      billingPeriod: "فترة الفوترة",
    },

    languageDropdown: {
      selectLanguagesLabel: "اللغات",
      selectLanguagesDescription: "حدد اللغات التي تتحدثها",
      searchPlaceholder: "ابحث باسم الدولة...",
      selectedCounter: "المحدد",
      maximumSelected: "تم الوصول للحد الأقصى",
      loadingLanguages: "جاري تحميل اللغات...",
      failedToLoadLanguages: "فشل تحميل اللغات",
      noLanguagesFound: "لم يتم العثور على لغات",
      selectLanguagesYouSpeak: "حدد اللغات التي تتحدثها",
      selectLanguages: "اختر اللغات",
    },
    currency: {
      name: "الدينار الأردني",
      code: "د.ا",
      symbol: "د.ا",
    },

    tripDetailScreen: {
      pickupLocation: "مكان الانطلاق",
      dropoffLocation: "مكان الوصول",
      tripDate: "تاريخ الرحلة",
      tripTime: "وقت الرحلة",
      numberOfSeats: "عدد المقاعد",
      luggageSize: "حجم الأمتعة",
      genderPreference: "تفضيل الجنس",
      waitingForOffers: "بانتظار العروض",
      waitingForOffersDesc:
        "السائقون الذين يطابقون مسارك سيقدمون عروضًا لرحلتك قريبًا",
      seeAvailableRides: "عرض الرحلات المتاحة",
      editRequest: "تعديل الطلب",
      cancelRequest: "إلغاء الطلب",
      backToHome: "العودة إلى الصفحة الرئيسية",
      cancelSuccess: "تم إلغاء طلب الرحلة بنجاح",
      ok: "حسنًا",
    },
    luggageSize: {
      small: "صغير",
      medium: "متوسط",
      large: "كبير",
    },
    genderPreference: {
      male: "ذكر",
      female: "أنثى",
      any: "أي",
      noPreference: "بدون تفضيل",
    },
    vehicleDetails: {
      title: "تفاصيل المركبة",
      trunkSize: "حجم صندوق الأمتعة",
      carModel: "طراز السيارة",
      vehicleType: "نوع المركبة",
      numberOfSeats: "عدد المقاعد",
    },
    rideSharedScreen: {
      rideDetails: "تفاصيل الرحلة",
      driver: "السائق",
      passenger: "الراكب",
      date: "التاريخ",
      from: "من",
      to: "إلى",
      fare: "الأجرة",
      reviews: "التقييمات",
      noRides: "لا توجد رحلات بعد",
    },
    rideCancelledScreen: {
      cancellationDetails: "تفاصيل الإلغاء",
      user: "المستخدم",
      date: "التاريخ",
      from: "من",
      to: "إلى",
      cancellationReason: "سبب الإلغاء",
      additionalComment: "تعليق إضافي",
      noCancelledRides: "لا توجد رحلات ملغاة",
      reasons: {
        priceHigher: "السعر أعلى من المتوقع",
        driverMisconduct: "سلوك السائق غير مناسب",
        lostItem: "فقدان غرض",
      },
    },

    driverFeedback: {
      priceHigher: "السعر أعلى من المتوقع؟",
      driverMisconduct: "سوء سلوك السائق",
      lostItem: "فقدان العنصر",
      addComment: "إضافة تعليق",
      feedbackPlaceholder: "اكتب تعليقك هنا...",
      submit: "إرسال",
      rideCancelled: "تم إلغاء الرحلة",
      feedbackSubmitted: "تم إرسال تعليقات الإلغاء بنجاح.",
    },
  },

  sendOfferModal: {
    sendOfferTo: "إرسال عرض إلى {{name}}",
    route: "{{pickup}} → {{destination}}",
    offerAmount: "مبلغ العرض ($)",
    enterOfferAmount: "أدخل مبلغ العرض",
    distance: "المسافة",
    seatsRequired: "عدد المقاعد المطلوبة",
    seat: "مقعد",
    seats: "مقاعد",
    sending: "جاري الإرسال...",
    sendOffer: "إرسال العرض",
    cancel: "إلغاء",
    offerRequiredTitle: "مطلوب عرض",
    offerRequiredMessage: "الرجاء إدخال مبلغ العرض",
    invalidAmountTitle: "مبلغ غير صالح",
    invalidAmountMessage: "الرجاء إدخال مبلغ صالح",
    sendingOfferTitle: "إرسال العرض",
    sendingOfferMessage: "يتم إرسال {{amount}}$ إلى {{name}}...",
    successTitle: "تم بنجاح",
    successMessage: "تم إرسال عرض بقيمة {{amount}}$ إلى {{name}}",
  },
};
