export default {
  onboarding: {
    slide1: {
      title: "Request a ride",
      description: "Get ready. Set ride.",
    },
    slide2: {
      title: "Find a ride",
      description: "Your ride, just a tap away.",
    },
    slide3: {
      title: "Request a ride",
      description: "Get ready, Set ride",
    },
    slide4: {
      title: "Post a ride",
      description: "Go Together, Save Together.",
    },
    slide5: {
      title: "Share your journey, save your costs",
      description:
        "Rakib helps you share trips across Jordan and split fuel expenses in a safe and smart way.",
    },
    slide6: {
      title: "Choose who you travel with",
      description:
        "Browse driver profiles, check reviews, and select the trip or driver that fits you best.",
    },
    slide7: {
      title: "Drive or ride, with one single account",
      description:
        "Easily switch between Passenger Mode and Driver Mode anytime, inside the same profile.",
    },
    slide8: {
      title: "Enable your location",
      description: "Choose your location to start.",
      locationAccessGranted: "Location Access Granted",
      locationAccessRequired: "Location Access Required",
      skipforNow: "Skip for now",
      allSet: "You're all set! Tap GO to continue.",
      pickupTimes:
        "We need your location to find nearby rides and provide accurate pickup times.",
      locationServiceDisabled: "Location Services Disabled",
      locationService:
        "Please enable location services in your device settings to continue.",
      locationPermission: "Location Permission Needed",
      appInfo:
        "This app needs your location to provide nearby services and accurate ride information. Please enable location access in settings.",
      go: "Go",
    },
  },
  auth: {
    signUp: {
      title: "Sign Up",
      agree1: "I agree to the",
      agree2: "Terms & Conditions",
      agree3: "and",
      agree4: "Privacy Policy",
      subtitle: "Create your account to get started",
      fields: {
        name: "FULL NAME",
        namePlaceholder: "Olivia Rae",
        userName: "USERNAME",
        userNamePlaceholder: "Letizia15",
        email: "EMAIL ADDRESS",
        emailPlaceholder: "Olivia321@gmail.com",
        phone: "PHONE NUMBER",
        phonePlaceholder: "+39 06 12345678",
        password: "PASSWORD",
        passwordPlaceholder: "********",
        confirmPassword: "CONFIRM PASSWORD",
        confirmPasswordPlaceholder: "********",
        location: "Location",
        locationPlaceholder: "2955 washterimer RD. santa area, sans Fransicco",
        bio: "Bio",
        bioPlaceholder: "Max 150 character...",
      },
      button: "SIGN UP",
      editButton: "Update Profile",
      googleButton: "Continue with Google",
      footer: {
        text: "Already have an account?",
        link: "Sign in",
      },
    },
    logIn: {
      title: "Sign in",
      subtitle: "Access to your account",
      fields: {
        email: "EMAIL ADDRESS",
        emailPlaceholder: "Olivia321@gmail.com",
        password: "PASSWORD",
        passwordPlaceholder: "********",
      },
      forgotPassword: "Forgot Password?",
      button: "LOG IN",
      or: "Or",
      googleButton: "Continue with Google",
      footer: {
        text: "Don't have an account?",
        link: "Sign Up",
      },
    },
    verifyNumber: {
      title: "Verify Phone Number",
      subtitle: "“Enter the SMS code we sent”",
      buttonTitle: "VERIFY",
      resend: "RESEND CODE",
      verifySuccessTitle: "Verification Successful!",
      verifySuccessSubtitle: "Your phone number has been verified successfully",
      continue: " Continue",
    },

    forgotPassword: {
      title: "Forgot Password",
      subtitle:
        "Please enter the email address to continue a verify your account.",
      send: "SEND",
    },

    verifyPassword: {
      title: "Verification Code",
      subtitle:
        "Please enter the 6 digit code sent to your email address ********r@gmail.com",
      modalTitle: "Congratulations!",
      modalSubtitle: "Password set successfully",
    },

    setPassword: {
      title: "Set New Password",
      subtitle: "Set your new password",
      passwordHeader: "Enter new Password",
      confirmPassword: "Confirm Password",
      buttonText: "RESET",
      modalSubtitle: "Password reset successfully.",
    },

    allButtonsName: {
      passenger: "Start as Passenger",
      driver: "Start as Driver",
    },

    shared: {
      genderTitle: "General Preferences",
      male: "Male",
      female: "Female",
      noPreference: "No Preference",
    },
  },

  tabs: {
    map: {
      bookNow: "Book Now",
      scheduleRide: "Schedule Ride",
      titlePlaceholder: "Where would you go?",
      pickUpLocation: "Pickup location",
      DroppingOff: "Dropping off",
    },
    profile: {
      editProfile: "Edit Profile",
      changePassword: "Change Password",
      savedDriver: "Saved Driver",
      payments: "Payments",
      preferences: "Preferences",
      helpAndSupport: "Help & Support",
      terms: "Terms and Conditions",
      privacy: "Privacy Policy",
      logout: "Logout",
      myvehicle: "My Vehicle",
      dashboard: "Dashboard",

      changePasswordScreen: {
        enterCurrentPass: "Enter Current Password",
        enterNewPass: "Enter New Password",
        enterconfirmPass: "Enter Confirm Password",
        changePass: "Save Changes",
      },
      changeLanguage: "Change Language",
      settings: "Settings",
      myRides: "My Rides",
    },
  },

  passenger: {
    availableRides: {
      confirmRide: "Confirm Ride",
      bookSeats: "Book",
      seat: "seat",
      seats: "seats",
      with: "with",
      total: "Total",
      genderPreference: "Gender Preference",
      male: "Male",
      female: "Female",
      any: "Any",
      chat: "Chat",
      call: "Call",
      bookNow: "Book Now",
      booked: "Booked",
      noRidesAvailable: "No rides available at the moment",
      backToTripRequest: "Back to Trip Request",
      numberOfSeats: "Number of Seats",
      seatsAvailable: "seats available",
      bookFullCar: "Book Full Car",
      openingChat: "Opening chat with",
      calling: "Calling",
      success: "Success",
      bookingSuccess: "seat(s) booked with",
    },
    tabs: {
      titles: {
        home: "Home",
        myTrip: "My Trips",
        chats: "Chats",
        profile: "Profile",
        messages: "Messages",
      },

      home: {
        driverRequestList: "Available Drivers  List",
        noDriverAvailable: "No drivers available",
        arrivingIn: "Arriving in",
        mins: "mins",
        chat: "Chat",
        call: "Call",
        accept: "Accept",
        cancel: "Cancel",
        ridesShared: "Rides Shared",
        cancelled: "Cancelled",
        ratings: "ratings",
        reviews: "Reviews",
        report: "Report",
        block: "Block",
        reportDriver: "Report Driver",
        selectReason: "Select a reason",
        submitReport: "Submit Report",
        describeTheIssue: "Please describe the issue",
        describeWhatHappend: "Describe what happened...",
        unsafeDriving: "Unsafe Driving",
        rude: "Rude behaviour",
        carCondition: "Car condition issues",
        conduct: "Inappropriate conduct",
        cancelledMultipleTimes: "Cancelled multiple times",
        other: "Other",
        blockDriver: "Block Driver?",
        confirm: "Are you sure you want to block",
        confirm2:
          "You won't be able to see their rides or communicate with them.",
        yesBlock: "Yes, Block Driver",
      },
      trip: {
        titles: {
          pickADate: "Pick a Date",
          pickATime: "Pick a Time",
          selectLuggage: "Select Luggage",
          selectPreferredGender: "Select Preferred Gender",
          tripSummary: "Trip Summary",
          tripDetails: "Trip Details",
          driverProfile: "Driver Profile",
          rideCancellation: "Ride Cancellation",
          termsConditions: "Terms and Conditions",
          privacyPolicy: "Privacy Policy",
          rating: "Rating",
          availableRides: "Available Rides",
          cancelledRides: "Cancelled Rides",
          ridesShared: "Rides Shared",
          aboutUs: "About Us",
        },

        selectDate: "SELECT DATE",
        selectTime: "SELECT TIME",
        howManyseats: "How many seats are you looking for?",
        luggageSize: "Luggage size",
        next: "Next",
        generalPreferences: "General Preferences",
        pickUplocation: "Pickup location",
        dropOffLocation: "Drop-off location",
        tripDate: "Departure Date",
        tripTime: "Departure Time",
        distance: "Distance",
        seat: "Seat",
        genderPreference: "Gender Preference",
        multiDaySelection: "Multi-stop Itinerary",
        yourRoute: "Your Route",
        stops: "Stops",
        stop: "Stop",
        addStop: "Add Stop",
        publishRequest: "Publish Request",
        chatWithDriver: "Chat with Driver",
        viewTrip: "View Trip",
        backtoHome: "Back to Home",
        selectedLocation: "Selected Locations",
        pickUp: "Pickup",
        dropoff: "Dropoff",

        cancelRide: "Cancel Ride",
        continue: " Continue",
        cancelModalTitle: "Are you sure you want to cancel?",
        yesBtn: "Yes",
        noBtn: "No",

        continueModalTitle: "You arrive at your destination",
        continueModalSubtitle: "Trip Completed",

        leaveReview: "Leave a review",
        goBack: "Go back",

        // Add selectDriver object here
        selectDriver: {
          confirmRide: "Confirm Ride",
          bookSeats: "Book",
          seat: "seat",
          seats: "seats",
          with: "with",
          total: "Total",
          success: "Success",
          bookedSuccess: "Booked",
          cancelRequest: "Cancel Request",
          areYouSureCancel: "Are you sure you want to cancel this request?",
          premiumFeature: "Premium Feature",
          callFeatureMessage:
            "Call feature is available for premium users only. Upgrade your account to unlock calling.",
          upgradeNow: "Upgrade Now",
        },
      },

      ratingScreenText: {
        headerTitle: "Rate Your Experience",
        headerSubtitle: "Your feedback helps us improve",
        ratingLabels: {
          1: "Poor",
          2: "Fair",
          3: "Good",
          4: "Very Good",
          5: "Excellent",
        },
        commentPlaceholder: "Write a short comment..",
        submitBtn: "Submit",
        notNowBtn: "Not Now",
      },

      profileScreenText: {
        currentModePrefix: "You are in ",
        passenger: "Passenger",
        driver: "Driver",
        modeSuffix: " Mode",
        enableDriverMode: "Enable Driver Mode",
        enablePassengerMode: "Enable Passenger Mode",

        titles: {
          profileSetup: "Profile Setup",
          editProfile: "Edit Profile",
          changePassword: "Change Password",
          savedDriver: "Saved Driver",
          payments: "Payments",
          cashInput: "Cash Input",
          transactionsHistory: "Transaction History",
          preference: "Ride Preference",
          helpAndSupport: "Help and Support",
        },

        logout: {
          logoutText:
            "Are you sure you want to logout? You'll need to sign in again to access your account.",
          logoutBtn: "Logout",
          cancel: "Cancel",
        },

        ridePreferenceScreenText: {
          ladiesOnlyPreference: "Ladies-only preference",
          luggazeSize: "Luggage size",
          conversationalPreference: "Conversational preference",
          talkative: "Talkative",
          quite: "Quiet",
          musicPreference: "Music preference",
          pet: "Pet friendly",
          saveBtn: "Save",
        },

        helpAndSupportScreenText: {
          frequentlyAskedQuestion: "Frequently Asked Questions",
          needMoreHelp: "Need More Help?",
          contactSupport: "Contact Support",
        },
      },

      paymentScreenTexts: {
        header: {
          amount: "Amount",
          availableBalance: "Available Balance",
          addNewCard: "+Add New Card",
          history: "History",
        },
        section: {
          selectPaymentMethod: "Select Payment Method",
        },
        methods: {
          cash: "Cash",
          wallet: "Wallet",
          paypal: "Paypal",
          card: "Credit Card",
          cliq: "CliQ",
          comingSoon: "Coming soon",
        },
        actions: {
          payWith: "Pay With",
          topUp: "Top Up",
          proceed: "Proceed",
          enterCash: "Enter cash",
        },
        modal: {
          notAvailableTitle: "Not Available Yet",
          notAvailableMessage:
            "{method} payment option is coming soon. Please use Cash for now.",
          gotIt: "Got It",
        },
      },
    },
  },

  driver: {
    rideDetail: {
      tripId: "Trip ID",
      pickup: "Pickup",
      dropoff: "Dropoff",
      dateTime: "Departure Date & Time",
      distance: "Distance",
      seats: "Seats",
      price: "Price",
      offeredPrice: "Offered Price",
      driver: "Driver",
      fullCarPrice: "Full Car Price",
    },

    profileLayoutTitleText: {
      driverProfileSetup: "Profile Setup",
      addVehicle: "Add Vehicle",
      addVehicleDetails: "Add Vehicle",
      vehicleSummary: "Car Details",
      passengerRqstList: "Passenger Request List",
      passengerRqstDetails: "Passenger Request Details",
    },
    driverProfileTexts: {
      nidUpload: "NID/License Upload",
      firstNameLabel: "First Name",
      firstNamePlaceholder: "Type your first name",
      lastNameLabel: "Last Name",
      lastNamePlaceholder: "Type your last name",
      licenseNumberLabel: "License number",
      licenseNumberPlaceholder: "License number",
      saveButton: "Save",
      permissionTitle: "Permission Required",
      permissionMessage:
        "Please grant permission to access your photo library.",
      uploadTitle: "Upload a clear photo",
      uploadMessage: "Choose your upload method",
      photoLibrary: "Photo Library",
      camera: "Camera",
      cancel: "Cancel",
      errorTitle: "Error",
      errorMessage: "Failed to pick file. Please try again.",
      tapToChange: "Tap to change file",
      clickToUpload: "Click to upload",
      label: "Date of Birth",
      placeholder: "MM/DD/YYYY",
      done: "Done",
      language: "Language",
      selectLanguage: "Select Langauge",
      governorateLabel: "Governorate",
      selectGovernorate: "Select your governorate",
      modalTitle: "Select Governorate",
      searchPlaceholder: "Search governorate...",
    },

    carImageUploadTexts: {
      permissionTitle: "Permission Required",
      permissionGallery: "We need camera roll permissions to upload images.",
      permissionCamera: "We need camera permissions to take photos.",
      removeImageTitle: "Remove Image",
      removeImageMessage: "Are you sure you want to remove this image?",
      cancel: "Cancel",
      remove: "Remove",
      addPhotosTitle: "Add Photos",
      addPhotosMessage: "Choose an option",
      takePhoto: "Take Photo",
      chooseFromGallery: "Choose from Gallery",
      addPhotoButton: "Add Photo",
      headerTitle: "Car Gallery",
      headerSubtitle: "Capture or upload your car photos",
      photo: "Photo",
      photos: "Photos",
      added: "Added",
      clearAllTitle: "Clear All Photos",
      clearAllMessage: "This will remove all photos from the gallery.",
      clearAllButton: "Clear All",
      galleryTitle: "Photo Gallery",
      noPhotos: "No photos yet",
      startMessage: "Start by taking a photo or uploading from gallery",
      gallery: "Gallery",
      close: "Close",
      delete: "Delete",
      navigationPrev: "Previous",
      navigationNext: "Next",
    },

    addVehicleDetails: {
      carModel: "Car Model",
      carModelPlaceholder: "e.g., Toyota Axio 2018",
      licensePlate: "License Plate",
      licensePlatePlaceholder: "e.g., DHA-123456",
      numberOfSeats: "Number of Seats",
      numberOfSeatsPlaceholder: "e.g. 4",
      save: "Save",
      vehicleType: "Vehicle Type",
      vehicleTypePlaceholder: "Select vehicle type",
      vehicleTypeTitle: "Select Vehicle Type",
      amenities: {
        ac: "AC",
        usb: "USB ports",
        wifi: "WiFi",
        smoking: "Smoking Allowed",
        music: "Music",
      },
    },

    vehicleSummary: {
      submit: "Submit",
      carModel: "Car Model",
      vehicleType: "Vehicle Type",
      numberOfSeats: "Number of Seats",
      trunkSize: "Trunk size",
      trunkSizeValue: "Medium",
      amenities: {
        ac: "AC",
        usb: "USB ports",
        wifi: "WiFi",
        smoking: "Smoking allowed",
        music: "Music",
      },
    },

    tabs: {
      labels: {
        upcoming: "Upcoming",
        ongoing: "Ongoing",
        requests: "My Requests",
        completed: "Completed",
        cancelled: "Cancelled",

        // Ride sections
        publishedRequest: "Published Rides",
        upcomingRides: "Upcoming Rides",
        ongoingRides: "Ongoing Rides",
        rideRequests: "Ride Requests",
        completedRides: "Completed Rides",
        cancelledRides: "Cancelled Rides",
      },
      editRequestModal: {
        editRequest: "Edit Request",
        tripId: "Trip ID",
        pickupAddress: "Pickup Address",
        searchPickup: "Search pickup location",
        dropoffAddress: "Dropoff Address",
        searchDropoff: "Search dropoff location",
        date: "Date",
        time: "Time",
        seats: "Seats",
        numberOfSeats: "Number of seats",
        cancel: "Cancel",
        saveChanges: "Save Changes",
        error: "Error",
        fillAllFields: "Please fill in all required fields",
      },
      upcomingScreen: {
        emptyTitle: "No upcoming rides",
        editTime: "Edit Time",
        viewDetails: "View Details",
        rideId: "Ride",
        at: "at",
        status: {
          upcoming: "Upcoming",
          ongoing: "Ongoing",
          completed: "Completed",
          cancelled: "Cancelled",
        },
        seats: "Seats",
        available: "Available",
        pricePerSeat: "Price/Seat",
        fullCar: "Full Car",
        ac: "AC",
        yes: "Yes",
        no: "No",
        seatsBooked: "Seats Booked",
        contact: "Contact",
        cancel: "Cancel",
        noUpcomingRides: "No Upcoming Rides",
        noUpcomingRidesMessage: "You don't have any upcoming rides scheduled",
      },

      ongoingRides: {
        emptyTitle: "No ongoing rides",
        contactDriver: "Contact Driver",
        cancel: "Cancel",
        cancelTitle: "Cancel Ride",
        cancelMessage: "Are you sure you want to cancel this ride?",
        no: "No",
        yesCancel: "Yes, Cancel",
        rideId: "Ride",
        pricePerSeat: "Price per Seat",
        seatsBooked: "Seats Booked",
        contact: "Contact",
        success: "Success",
        rideMarkedComplete: "Ride marked as completed",
        noOngoingRides: "No Ongoing Rides",
        noOngoingRidesMessage: "No ongoing rides at the moment",
      },

      requests: {
        emptyTitle: "No ride requests",
        accept: "Accept",
        decline: "Decline",
        successTitle: "Success",
        successMessage: "Request accepted! Driver will contact you soon.",
        rejectTitle: "Request Rejected",
        rejectMessage: "You have declined this ride request.",
        ok: "OK",
      },

      requestsScreen: {
        successTitle: "Success",
        acceptedOffer: "You accepted the driver's offer",
        rejectTitle: "Request Rejected",
        rejectMessage: "You have declined this ride request.",
        ok: "OK",
        success: "Success",
        requestUpdated: "Request updated successfully",
        accept: "Accept",
        decline: "Decline",
        edit: "Edit",
        cancel: "Cancel",
        emptyTitle: "No ride requests",
      },

      completedScreen: {
        emptyTitle: "No completed rides",
        rateDriver: "Rate Driver",
        viewReceipt: "View Receipt",

        rideId: "Ride",
        at: "at",
        status: {
          upcoming: "Upcoming",
          ongoing: "Ongoing",
          completed: "Completed",
          cancelled: "Cancelled",
        },
        seats: "Seats",
        available: "Available",
        pricePerSeat: "Price/Seat",
        fullCar: "Full Car",
        ac: "AC",
        yes: "Yes",
        no: "No",
        seatsBooked: "Seats Booked",
        rideCompletedSuccessfully: "Ride Completed Successfully",
        noCompletedRides: "No Completed Rides",
        noCompletedRidesMessage: "You don't have any completed rides yet",
        reviewPassenger: "Review Passenger",
      },
      cancelledScreen: {
        emptyTitle: "No cancelled rides",
        bookAgain: "Book Again",
        viewDetails: "View Details",

        rideId: "Ride",
        at: "at",
        status: {
          upcoming: "Upcoming",
          ongoing: "Ongoing",
          completed: "Completed",
          cancelled: "Cancelled",
        },
        seats: "Seats",
        available: "Available",
        pricePerSeat: "Price/Seat",
        fullCar: "Full Car",
        ac: "AC",
        yes: "Yes",
        no: "No",
        seatsBooked: "Seats Booked",
        rideCancelled: "Ride Cancelled",
        noCancelledRides: "No Cancelled Rides",
        noCancelledRidesMessage: "You don't have any cancelled rides",
      },
      membershipPlans: {
        header: "Choose Your Plan",
        subheader: "Select the perfect membership plan",
        popular: "Popular",
        planBenefitsTitle: "Plan Benefits",
        planBenefits:
          "• Cancel anytime with no hidden fees\n• 14-day money-back guarantee\n• Upgrade or downgrade plans easily\n• Secure payment processing",
        freePlan: {
          name: "Free Plan",
          buttonText: "Start free",
          features: [
            "3 rides monthly",
            "Send requests",
            "Basic profile",
            "In app chat",
          ],
        },
        premium: {
          name: "Premium",
          title: "Everything in Free Plan +",
          buttonText: "Upgrade",
          features: [
            "Unlimited rides in one mode: Passenger or Driver",
            "Blue verified badge",
            "Safety filters: gender and verified user",
            "Higher visibility than Free users",
            "In-app voice calls",
          ],
        },
        allAccess: {
          name: "All Access",
          title: "Everything in Premium Plan +",
          buttonText: "Go All Access",
          features: [
            "Unlimited rides in both modes: Passenger and Driver",
            "Gold badge",
            "Higher visibility than Premium users",
            "Switch modes anytime without limits",
            "Higher ranking in search results",
          ],
        },
        premiumPlus: {
          name: "Premium Plus",
          title: "Everything in All Access Plan +",
          buttonText: "Get Plus",
          features: [
            "Purple badge",
            "Top visibility: highest priority",
            "Featured placement in search results",
            "Premium support: direct chat with admin",
            "Full access to rewards and future benefits",
            "Early access to new features",
          ],
        },
      },

      homeScreenText: {
        publishARide: "Publish a Ride",
      },
      passengerRequestList: {
        successTitle: "Success",
        reportSubmitted: "Report submitted successfully",
        passengerBlocked: "Passenger has been blocked",
        seats: "seats",
        km: "km",
        openRequest: "Open Request",
        reportUser: "Report User",
        blockUser: "Block User",
      },
      earnings: {
        estEarnings: "Estimated earnings",
      },
      passengerRequestDetails: {
        pickupLocation: "Pickup location",
        dropoffLocation: "Drop-off location",
        tripDate: "Trip date",
        tripTime: "Trip time",
        distance: "Distance",
        seat: "Seat",
        luggageSize: "Luggage size",
        genderPreference: "Gender preference",
        multiDaySelection: "Multi-day selection",
        sendOffer: "Send Offer",
      },
      sendOfferModal: {
        typeYourOffer: "Type your offer",
        placeholder: "Type your offer here (in JOD)",
        cancel: "Cancel",
        text1_empty: "Empty Offer",
        text2_empty: "Please enter your offer before submitting",
        text1_sending: "Sending Offer",
        text2_sending: "Please wait...",
        text1_success: "Offer Sent Successfully",
        text2_success:
          "Your offer has been sent to the passenger. We will notify you when they respond.",
      },

      completedRides: {
        completedRidesFor: "Completed Rides for",
        noRides: "No rides for this month.",
        months: {
          january: "January",
          february: "February",
          march: "March",
          april: "April",
          may: "May",
          june: "June",
          july: "July",
          august: "August",
          september: "September",
          october: "October",
          november: "November",
          december: "December",
        },
      },

      upcomingRides: {
        header: "Upcoming rides",
        noRides: "No rides scheduled for this date.",
      },

      editRoutes: {
        required: "Required",
        enterPickupLocation: "Please enter pickup location",
        enterDropoffLocation: "Please enter drop-off location",
      },
      map: {
        bookNow: "Book Now",
        scheduleRide: "Schedule Ride",
        titlePlaceholder: "Where would you go?",
        pickUpLocation: "Pickup location",
        DroppingOff: "Dropping off",
      },
      location: {
        permissionDenied: "Permission Denied",
        permissionRequired:
          "Location permission is required to use this feature.",
        error: "Error",
        unableToGetLocation: "Unable to get current location",
        unableToGetLocationDetails: "Unable to get location details",
        selectedLocations: "Selected Locations:",
        pickup: "Pickup:",
        dropoff: "Dropoff:",
        latitude: "Lat",
        longitude: "Lng",
      },
      myTrip: {
        screenTitles: {
          bookDate: "Pick a Date",
          bookTime: "Pick a Time",
          passengerProfile: "Passenger Profile",
        },

        publishedRides: {
          header: "My Published Rides",
          activeRides: "ride",
          activeSuffix: " active",
          noActiveRides: "No active rides",
          completedAndCancelledMessage:
            "Your completed and cancelled rides are not shown here",
          editRideModal: "Edit Ride",
          saveChanges: "Save Changes",
          cancel: "Cancel",
          selectLocation: "Select location",
          selectDate: "Select date",
          selectTime: "Select time",
          pickupLabel: "Pickup Location",
          dropoffLabel: "Dropoff Location",
          dateLabel: "Trip Date",
          timeLabel: "Trip Time",
          seatsLabel: "Number of Seats",
          pricePerSeatLabel: "Price Per Seat (JOD)",
          fullCarPriceLabel: "Full Car Price (JOD)",
          acLabel: "Air Conditioning",
          editButton: "Edit",
          cancelButton: "Cancel",
          markCompleted: "Mark as Completed",
          deleteConfirmTitle: "Cancel Ride",
          deleteConfirmMessage: "Are you sure you want to cancel this ride?",
          deleteConfirmNo: "No",
          deleteConfirmYes: "Yes, Cancel",
          updateSuccess: "Success",
          updateSuccessMessage: "Ride details updated successfully!",
          locationPickerTitle: "Select Pickup",
          locationPickerSubtitle: "Select Dropoff",
          searchLocation: "Search location...",
          noLocationsFound: "No locations found",
          latitudeLabel: "Lat",
          longitudeLabel: "Lng",
        },

        // For RideCard component translations
        rideCard: {
          seats: "Total Seats",
          available: "Available",
          perSeat: "Per Seat",
          fullCar: "Full Car",
          ac: "AC",
          acYes: "✓ Yes",
          acNo: "✗ No",
          pending: "Pending",
          ongoing: "Ongoing",
          completed: "Completed",
          cancelled: "Cancelled",
        },

        numberOfSeat: "Number of Seat",
        numberOfSeatPlaceholder: "e.g. 1 seat/Full car",
        pricePerSeat: "Price per seat",
        pricePerSeatPlaceholder: "e.g. 1 seat/Full car",
        fullCarPrice: "Full car price",
        fullCarPricePlaceholder: "e.g. 40 JOD for the full car",
        ladiesOnlyPreference: "Ladies-only preference",
        next: "Next",
        publishSuccess: {
          title: "Your ride has been published.",
          subtitle: "We will notify you when your ride is accepted.",
          done: "Done",
        },
      },
      profileScreenText: {
        screenTitles: {
          editProfile: "Edit Profile",
          myVehicle: "My Vehicle",
          dashboard: "Overview",
          editAvailability: "Edit Availability",
          editRoutes: "Edit Routes",
          changeMembership: "Choose Membership",
          completedRides: "Completed Rides",
          upcomingRides: "Upcoming Rides",
          estimateEarning: "Earnings",
        },
      },
      overview: {
        completedRides: "Completed\nrides",
        upcomingRides: "Upcoming\nrides",
        estimatedEarnings: "Estimated\nearnings",
        editAvailability: "Edit Availability",
        editRoutes: "Edit Routes",
        viewPassengersRequestList: "Passenger Requests",
        changeMembership: "Change Membership",
        availability: "Availability",
      },
    },
  },

  languageChange: {
    header: "Language Preferences",
    selectYourPreferredLanguage: "Select your preferred language for the app",
    currentLanguage: "Current Language",
    chooseLanguage: "Choose Language",
    languageInfo: "Language Settings",
    languageDescription:
      "Your selection will be saved and applied across the entire app. You can change this anytime.",
    selectedLanguage: "Selected Language Details",
    languageName: "Language Name",
    languageCode: "Language Code",
  },

  shared: {
    rakibPaymentForm: {
      unlimitedModeModal: {
        selectMode: "Select mode",
        passengerModeOnly: "Passenger mode only",
        driverModeOnly: "Driver mode only",
      },
      titles: {
        premium: "Upgrade to Premium Plan",
        allAccess: "Upgrade to All Access Plan",
        premiumPlus: "Upgrade to Premium Plus Plan",
      },
      chooseUnlimitedMode: "Choose your unlimited mode",
      selectMode: "Select mode",
      wantUnlimitedRides:
        "Want unlimited rides in both Passenger and Driver modes?",
      upgradeToAllAccess: "Upgrade to All Access",
      rakibUsername: "Rakib username",
      rakibUsernamePlaceholder: "Type your username",
      fullName: "Full name",
      fullNamePlaceholder: "Type your full name",
      emailUsedOnRakib: "Email used on Rakib",
      emailPlaceholder: "Type your email..",
      phoneNumberInternational: "Phone number (international)",
      phoneNumberPlaceholder: "+962...",
      payNowWithCreditCard: "Pay now with credit card (coming soon)",
      receivePaymentInfoByEmail: "Receive payment info by email",
      monthly: "Monthly, 4 JOD",
      yearly: "Yearly, 40 JOD",
      billingPeriod: "Billing period",
    },

    formSheet: {
      formsheetTitle: "What would you like to do?",
    },

    languageDropdown: {
      selectLanguagesLabel: "Languages",
      selectLanguagesDescription: "Select the languages you speak",
      searchPlaceholder: "Search by country name...",
      selectedCounter: "Selected",
      maximumSelected: "Maximum selected",
      loadingLanguages: "Loading languages...",
      failedToLoadLanguages: "Failed to load languages",
      noLanguagesFound: "No languages found",
      selectLanguagesYouSpeak: "Select languages you speak",
      selectLanguages: "Select Languages",
    },

    currency: {
      name: "Jordanian Dinar",
      code: "JOD",
      symbol: "JOD",
    },
    tripDetailScreen: {
      pickupLocation: "Pickup Location",
      dropoffLocation: "Drop-off Location",
      tripDate: "Trip Date",
      tripTime: "Trip Time",
      numberOfSeats: "Number of Seats",
      luggageSize: "Luggage Size",
      genderPreference: "Gender Preference",
      waitingForOffers: "Waiting for offers",
      waitingForOffersDesc:
        "Drivers matching your route will soon offer rides for your trip",
      seeAvailableRides: "See Available Rides",
      editRequest: "Edit Request",
      cancelRequest: "Cancel Request",
      backToHome: "Back to Home",
      cancelSuccess: "Trip request cancelled successfully",
      ok: "OK",
    },
    luggageSize: {
      small: "Small",
      medium: "Medium",
      large: "Large",
    },
    genderPreference: {
      male: "Male",
      female: "Female",
      any: "Any",
      noPreference: "No Preference",
    },
    driverFeedback: {
      priceHigher: "Price higher than expected?",
      driverMisconduct: "Driver misconduct",
      lostItem: "Lost Item",
      addComment: "Add comment",
      feedbackPlaceholder: "Write your feedback here...",
      submit: "Submit",
      rideCancelled: "Ride Cancelled",
      feedbackSubmitted: "Your cancellation feedback has been submitted.",
    },
    rideSharedScreen: {
      rideDetails: "Ride Details",
      driver: "Driver",
      passenger: "Passenger",
      date: "Date",
      from: "From",
      to: "To",
      fare: "Fare",
      reviews: "Reviews",
      noRides: "No rides yet",
    },
    rideCancelledScreen: {
      cancellationDetails: "Cancellation Details",
      user: "User",
      date: "Date",
      from: "From",
      to: "To",
      cancellationReason: "Cancellation Reason",
      additionalComment: "Additional Comment",
      noCancelledRides: "No cancelled rides",
      reasons: {
        priceHigher: "Price higher than expected",
        driverMisconduct: "Driver misconduct",
        lostItem: "Lost item",
      },
    },

    vehicleDetails: {
      title: "Vehicle Details",
      trunkSize: "Trunk Size",
      carModel: "Car Model",
      vehicleType: "Vehicle Type",
      numberOfSeats: "Number of Seats",
    },
  },

  sendOfferModal: {
    sendOfferTo: "Send Offer to {{name}}",
    route: "{{pickup}} → {{destination}}",
    offerAmount: "Offer Amount ($)",
    enterOfferAmount: "Enter your offer amount",
    distance: "Distance",
    seatsRequired: "Seats Required",
    seat: "Seat",
    seats: "Seats",
    sending: "Sending...",
    sendOffer: "Send Offer",
    cancel: "Cancel",
    offerRequiredTitle: "Offer Required",
    offerRequiredMessage: "Please enter an offer amount",
    invalidAmountTitle: "Invalid Amount",
    invalidAmountMessage: "Please enter a valid offer amount",
    sendingOfferTitle: "Sending Offer",
    sendingOfferMessage: "Sending ${{amount}} to {{name}}...",
    successTitle: "Success",
    successMessage: "Offer of ${{amount}} sent to {{name}}",
  },
};
